version: "3"
services:
  client:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ijartbank-admin
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - /app/node_modules
